version: '3'
services:
  database:
    container_name: project_postgres
    build: 
      context: ./
      dockerfile: ./devops/postgres/Dockerfile
    restart: always
    env_file:
      - database.env
    networks:
      - postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data/ # persist data even if container shuts down
  # a nice admin for pg (mostly for development)
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    name: postgres
    driver: bridge
volumes:
  pgadmin: # named volumes can be managed easier using docker-compose
  pg:
